### ISSUE TITLE
Sverchok menu changed!!!

### ISSUE THREAD

**Issue by nortikin** [vicdoval/sverchok-open3d#12]
https://github.com/nortikin/sverchok/blob/master/index.yaml
Please, take in account

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/commit/8192dcdd6de89908e2541432f688949a13ca252a also changes influence on registration. please, follow also sverchok chat https://t.me/sverchok_3d

**Comment by vicdoval** [comment]
Fixed
