### ISSUE TITLE
Error activation if no dependencies are installed

### ISSUE THREAD

**Issue by satabol** [vicdoval/sverchok-open3d#15]
If no dependencies installed then this addon do not activate itself or reset Blender.

![image](https://github.com/vicdoval/sverchok-open3d/assets/14288520/be1c7a8c-e45c-4068-9ad3-9fe01a5aeb18)

**Comment by satabol** [comment]
Hi @vicdoval . I like your addon. Can you append me to contributors ?

**Comment by satabol** [comment]
It is very strange: I create new request PR for this issue and it is disappear. @vicdoval Do you see it?

![image](https://github.com/vicdoval/sverchok-open3d/assets/14288520/42936fa2-6183-45d4-8f9b-392a5fedccb7)

**Comment by vicdoval** [comment]
> It is very strange: I create new request PR for this issue and it is disappear. @vicdoval Do you see it?
> 
> ![image](https://private-user-images.githubusercontent.com/14288520/311509107-42936fa2-6183-45d4-8f9b-392a5fedccb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODkyODQsIm5iZiI6MTcxMDA4ODk4NCwicGF0aCI6Ii8xNDI4ODUyMC8zMTE1MDkxMDctNDI5MzZmYTItNjE4My00NWQ0LThmOWItMzkyYTVmZWRjY2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE2NDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTI4NzRhM2QyNzE4YWRiNzZjZTFkMzU2NTI0OTI3NmI5MDM2YzI1YzU5MzU5ZTViODU5NDVmODk1ODdjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uajMUrNFlhkqytYZM9xWzwBbnutZg7S465dpNS1O3oU)

I do not see it, neither in your profile as activity...

**Comment by vicdoval** [comment]
I would rather have the dummy class in Sverchok than de-activating the addon

**Comment by vicdoval** [comment]
> Hi @vicdoval . I like your addon. Can you append me to contributors ?

You are already a contributor. You mean to add you as a collaborator?

**Comment by satabol** [comment]
> You are already a contributor. You mean to add you as a collaborator?

Yes. I'd like to create a PR into PR tab.

**Comment by satabol** [comment]
I can create PR now. Thank you!
